# Default values for helmmysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mysql:
    name: mysqldb
    image:
        repository: grethinam/my-mysql
        tag: latest
        pullPolicy: Always
        imagePullSecrets: mydockerhubregistrykey
    type: ClusterIP
    containerPort: 3306